### ISSUE TITLE
Translation Issues

### ISSUE THREAD

**Issue by rudahee** [rudahee/Metallics-Arts#1]
The section headings and the last sentence of the introduction are not translated into English.

![image](https://user-images.githubusercontent.com/35822076/197624146-b77b1c74-65a9-481a-8cf0-1e32030c23b4.png)
![image](https://user-images.githubusercontent.com/35822076/197624200-54068434-f260-405e-8b66-fccc20d3b5eb.png)

**Comment by ElPandaP** [comment]
"they" in lower case at the feruchemic rings chapter
![image](https://user-images.githubusercontent.com/116599304/197630134-418d3a66-def1-4186-86a9-377ae5a7960a.png)

**Comment by rudahee** [comment]
¡Buenas @ElPandaP!

Ya se han solucionado todos los problemas relacionados con la traducción ¡Por favor, sigue testeando!

Puedes encontrar la ultima [release aqui](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0) o en CurseForge en unas horas.

¡Nos vemos!
