### ISSUE TITLE
Vials issues

### ISSUE THREAD

**Issue by guillerbm7** [rudahee/Metallics-Arts#10]
Los viales se pueden beber de manera infinita aunque estén vacíos. No queda muy claro cómo se rellenan y el crafteo de vial+metal nugget funciona a veces.

**Comment by TobibusFate** [comment]
- El vial vacío se consume infinito pero no da reservas verdad ?
- Respecto al crafteo, se te bloquea luego de cargar algunos metales ? o se bloquea la primera vez que intentas cargarlos ?

**Comment by guillerbm7** [comment]
Sí, el vial se consume siempre aún estando vacío, reservas da, eso sí. 

Acabo de probar en creativo en otro mundo los crafteos y sí me funcionan correctamente y los sobreescribe si meto otro metal. En servidor (y survival) cuando probé, fallaban estas dos cosas con el hierro.

No sé si estará pensadas, os lanzo un par de ideas: 
- Que se gasten los viales al usarlos una o x veces.
- Que se indique qué metal tienen.

**Comment by TobibusFate** [comment]
Estoy ya mirando lo de que no te deje usar el vial vacío, pero ten en cuenta que si estas en creativo, puedes ponerles metales infinitos y no se te consume al usarlo (porque así funciona el creativo)
Respecto a ver los metales que contiene, es con el Ctrl, ya en la próxima versión se pondrá un mensaje que te lo indique

**Comment by rudahee** [comment]
Gracias por tus comentarios @guillerbm7 

Se ha solucionado en [la ultima release](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0)

Estará disponible en CurseForge en unas horas.
