### ISSUE TITLE
Objetos metálicos, caballos  y dudas en el archivo

### ISSUE THREAD

**Issue by LeandrOwO** [rudahee/Metallics-Arts#13]
Buenas! 
 
Añado estos candidatos a la lista, copypasteando lo que funcionó en pruebas al archivo MetallicsPowersConfig.java.

<details><summary>Metales añadidos</summary>
<p>
       
        add("lead_");
        add("nickel_");
        add("tin_");
        // Estos entiendo abarcan todos bloques de ese metal? El tin estaba así

        add(Items.SPYGLASS.getDescription().toString());
        add(Items.GLISTERING_MELON_SLICE.getDescription().toString());
        add(Items.NAME_TAG.getDescription().toString());

        add(Items.ARROW.getDescriptionId());
        add(Items.ARROW.getDescription().toString());

        add(Items.TIPPED_ARROW.getDescriptionId());
        add(Items.TIPPED_ARROW.getDescription().toString());

        add(Items.SPECTRAL_ARROW.getDescriptionId());
        add(Items.SPECTRAL_ARROW.getDescription().toString());

        add(Items.TRIDENT.getDescriptionId());
        add(Items.TRIDENT.getDescription().toString());

        add(Items.LIGHTNING_ROD.getDescriptionId());
        add(Items.LIGHTNING_ROD.getDescription().toString());

        add(Items.SOUL_LANTERN.getDescriptionId());
        add(Items.SOUL_LANTERN.getDescription().toString());
        // El lightning rod y la soul lantern no cuentan como bloque metálico a criterio del Vertical push/jump
</p>
</details>

// Falta poder empujar y tirar de los caballos con armadura de hierro y oro, y tirar de las flechas? Que entiendo que se comportan como entitys con propiedades...

Y en línea 21 de ese mismo archivo, el loop verifica que el metal NO sea estaño?
 
```
for (MetalsNBTData metals : MetalsNBTData.values()) {
            if (!metals.equals(MetalsNBTData.TIN)&&!metals.equals(MetalsNBTData.ALUMINUM)){
                add(metals.getNameLower());
```

 Si es así, ¿por qué?

Gracias y saludos! El mod es una obra de arte, intento reportar/aportar lo que vamos probando en un server de dos

**Comment by TobibusFate** [comment]
Buenas!
Ese código es del nuestro o es añadido tuyo ?
Con lo del empuje vertical esta el problema que para el efecto de salto no usa los bloques que tengas debajo exactamente, asique puede ser difícil verlo, pero es casi seguro que los use
Respecto al tin, esta colocado como "tin_" para evitar que tome objetos que contengan la palabra "tin", como enchanting table, y otros
Lo de las armaduras de caballos me lo mirare de agregar, que se me paso por alto jajaj 
El for agrega los nombres de metales que sean distintos de TIN y de ALUMINUM, ya que el tin lo agregamos con la linea del "tin_" y el aluminio no se puede empujar ni tirar (y si el for no hiciera esa consulta, los añadiría a la lista de metales que interactúan con empujones y tirones)

**Comment by rudahee** [comment]
@LeandrOwO Es algo complejo de explicar, lo que hace actualmente es ver al bloque al que esta mirando en el eje x-z (como si fuera 2D) y busca en diagonal 7 bloques hacia abajo. es una de las cosas que queremos reformular. 

Igualmente si hay un cambio que te parezca interesante (En la lista de metales, en hacer que el vuelo sea mas comodo, o la lever/button) hazte un fork limpio de nuestra ultima version, agrega las clases y haznos un pull request de tus cambios ¡Los vamos a revisar encantados!

Si te ves valiente, nos puedes hacer un pull request de las clases en especifico, pero no se como git maneja ese tipo de PR. 

Si quieres hablar o consultar algo mas rapidamente, puedes hacerlo en nuestros discords (Estan en la nota final del readme o de la web de CurseForge) 

Un besi de fresi por tus comentarios. <3

**Comment by TobibusFate** [comment]
Como ya fue resuelta la duda y el resto esta bien, no implementaremos por ahora lo de los caballos ya que causaría una disminución de rendimiento importante. Si mas adelante podemos implementarlo sin este problema, lo haremos 

Saludos!
