### ISSUE TITLE
Areglen

### ISSUE THREAD

**Issue by lucas300nes** [rudahee/Metallics-Arts#14]
-Con peltre feruquimico igual no se puede usar la espada de koloss
-El oro alomantico con duralumin, si moriste en el nether te teletransporta al lugar donde moriste en el mundo vanilla

**Comment by TobibusFate** [comment]
¡Buenas @lucas300nes!

Ya se ha implementado el uso de la espada koloss con peltre feruquimico y se ha arreglando el problema de viaje entre dimensiones del oro alomantico ¡Por favor, sigue testeando!

Puedes encontrar la ultima  versión [1.3.0] en CurseForge.

¡Nos vemos!
