### ISSUE TITLE
Duralumín con una sola pepita

### ISSUE THREAD

**Issue by Nagatosuke** [rudahee/Metallics-Arts#15]
Se puede utilizar el boost del duralumín con una sola pepita del metal (Solo lo he probado con la aleación de oro/plata)

**Comment by TobibusFate** [comment]
Buenas @Nagatosuke ^^

Ya esta implementada la solución a este problema, haciendo que tengas que llenar al máximo las reservas para usarlo.
Puedes encontrar la nueva version [1.3.0] en CurseForge

Que lo disfrutes !
