### ISSUE TITLE
Crash when picking up a dead player's metalmind

### ISSUE THREAD

**Issue by izan302** [rudahee/Metallics-Arts#16]
The error pops when you put the cursor on top of a dead player metalmind. 

The error : 

The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_7755_()" because the return value of "net.minecraft.world.level.Level.m_46003_(java.util.UUID)" is null

**Comment by TobibusFate** [comment]
Hi!

Thanks for the warning, we are already solving it for the next version ^^

**Comment by TobibusFate** [comment]
¡Hey @izan302 !

The new version of the mod has already been uploaded with this problem fixed ^^
You can find it on CurseForge

Thanks for the report
