### ISSUE TITLE
Guide book issues

### ISSUE THREAD

**Issue by ElPandaP** [rudahee/Metallics-Arts#2]
The guide book doesn't show koloss blade craft
![image](https://user-images.githubusercontent.com/116599304/197629777-94f5bc7d-b610-4ce5-be50-3efef5eacd6c.png)
![image](https://user-images.githubusercontent.com/116599304/197629818-fe49895d-1983-445f-a679-9023f62b8f11.png)

**Comment by rudahee** [comment]
Some spanish faults:

portada: error en comillas de dios
armas: se puede quitar el titulo del arma en la pagina del crafteo (para no repetir tanto)
bendaleo : acelera el mundo a tu alrededor?
cadmio tambien ?
nicrosil: subir el extra
el atium esta alreves, almacenar te hace brillar
bronce, los phantoms te ignoran, pero se generan igual ??
ettmetal, no reduce el daño de las explosiones
laton: agregar extra, biomas frios y nieve en polvo

**Comment by rudahee** [comment]
¡Buenas @ElPandaP!

Ya se han solucionado todos los problemas relacionados con la traducción ¡Por favor, sigue testeando!

Puedes encontrar la ultima [release aqui](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0) o en CurseForge en unas horas.

¡Nos vemos!
