### ISSUE TITLE
Saltar tappeando la mente de hierro

### ISSUE THREAD

**Issue by LeandrOwO** [rudahee/Metallics-Arts#20]
Buenas!

 Mientras tappeas la mente de hierro, el salto se deshabilita A MENOS que estés corriendo, en cuyo caso das un corto dash hacia adelante. No es un salto, pero dudo que sea una feature escondida jajaj

 Saludos!

**Comment by TobibusFate** [comment]
Eso es intencional, ya que decantas tu peso de la mente de hierro, te mueves mas lento y no puedes saltar.

Saludos!

**Comment by LeandrOwO** [comment]
Sé que eso es intencional, el bug es justamente que si estás corriendo, el "salto" es un dash hacia adelante
