### ISSUE TITLE
Bronce alomántico en servidor dedicado

### ISSUE THREAD

**Issue by LeandrOwO** [rudahee/Metallics-Arts#21]
No se dibuja la linea hacia un jugador quemando algún metal, jugando en un server forge (NO Open to LAN desde cliente), ni se remarca.

 También, como idea en un futuro, se podría añadir un tono que se emita desde el que se está detectando? En el servidor del Club sería un caos tho jajaj

**Comment by TobibusFate** [comment]
Buenas @LeandrOwO !
Ya arreglamos el problema de las líneas, asique ya deberían verse sin problema c:
La versión actual (1.4) ya tiene los cambios agregados
