### ISSUE TITLE
Los bloques de ettmetal no desaparecen luego de explotar.

### ISSUE THREAD

**Issue by Didaco795** [rudahee/Metallics-Arts#25]
https://user-images.githubusercontent.com/118015877/201411266-8cd26164-f8ba-43d9-ab9b-da40fee0a711.mp4

Prueba fehaciente de mis afirmaciones.

**Comment by TobibusFate** [comment]
Los bloques ya desaparecen al explotar ^^
Y la versión con los cambios ya esta disponible
