### ISSUE TITLE
Nombre de los bloques de las geodas

### ISSUE THREAD

**Issue by JavierBagatoli** [rudahee/Metallics-Arts#26]
Los bloques minado con picos de toque de sada, al tenerlo por item no dan un nombre sensillo

Podria ser bloque de Atium cristalizado por ejemplo (Entiendo que pasa lo mismo con los otros dos tipos)

![imagen](https://user-images.githubusercontent.com/73254517/201473420-8e643f63-58a6-46b1-aa05-f5b3e628d1a5.png)

**Comment by Didaco795** [comment]
Yo podría encargarme de traducirlos, juntamente con arreglar algunos errores ortográficos menores de otros objetos y también pulir el propio libro verde ese que te explica los crafteos de las mentes de metal, de las armas y demás.

Aunque necesitaría que me pasarais los archivos de texto, como la última vez.

**Comment by Didaco795** [comment]
@Sregio03 @rudahee ahora sí:

> diría de quitar las mayúsculas en "cristalizado" en todas las versiones excepto en la inglesa y la rusa, porque no es correcto gramaticalmente hablando. Y no hay otros objetos con mayúsculas donde no las hay, solo esos, así que quedaría mal.

Y recordando otras cosas, hay más objetos con faltas leves de ortografía. Repito: si me pasáis los documentos con los nombres de los objetos, os lo puedo arreglar en un pis pas.

**Comment by TobibusFate** [comment]
Buenas!
Ya se arreglaron los problemas de traducción ty @Didaco795 !
La versión ya esta disponible
