### ISSUE TITLE
El empuje continuo con pepitas de Aluminio

### ISSUE THREAD

**Issue by JavierBagatoli** [rudahee/Metallics-Arts#27]
Puedo empujarme continuamente usando pepitas de aluminio a modo de monedas.

**Comment by Sregio03** [comment]
Hola muy buenas, podrías decirnos si el bug fue ocasionado en un servidor? Y en ser ese el caso, estas 100% seguro de que se trataba de pepitas de aluminio?

**Comment by JavierBagatoli** [comment]
150% nivel estaba grabando la explicacion de como usar el poder para subirlo, 
Y era mundo propio no en servidor

**Comment by TobibusFate** [comment]
Buenas @JavierBagatoli !
Ya se quito el empuje con las pepitas de aluminio (y las de plata también), la versión 1.4 ya tiene los cambios agregados ^^
