### ISSUE TITLE
Problemas con el modpack Basic - Mod disfuncional.

### ISSUE THREAD

**Issue by Didaco795** [rudahee/Metallics-Arts#28]
![imagen](https://user-images.githubusercontent.com/118015877/202291025-6403e2a8-0c1d-4cb2-b17e-53c64d9ece88.png)

Hay algún mod del modpack Basic que no funciona como debería.

Os dejo los archivos de reporte, por si os sirve de algo.

[crash-2022-11-16_21.44.23-fml.txt](https://github.com/rudahee/Metallics-Arts/files/10025606/crash-2022-11-16_21.44.23-fml.txt)
[latest.log](https://github.com/rudahee/Metallics-Arts/files/10025607/latest.log)

**Comment by rudahee** [comment]
Esto se ha solucinado
