### ISSUE TITLE
Bug con el mod "Backpacked"

### ISSUE THREAD

**Issue by Nagatosuke** [rudahee/Metallics-Arts#29]
Si usas pepitas de cobre para impulsarte con acero y luego abres la mochila, recuperas todas las pepitas que has gastado.

**Comment by TobibusFate** [comment]
Buenas!
Ya estamos revisando este error, que también ocurre cuando haces otras cosas en servidor

**### _La lógica del empuje esta realizada con un player tipo cliente, por lo que la eliminación de las pepitas no se refleja en el servidor_**

**Comment by TobibusFate** [comment]
Hi @Nagatosuke !
Ya se soluciono el problema con la mochila y cuando te desconectas del servidor ^^
