### ISSUE TITLE
Sugerencia, asignar teclas especificas a enceder/apagar metales

### ISSUE THREAD

**Issue by Nagatosuke** [rudahee/Metallics-Arts#30]
Como ejemplo al hacer Shift + 1, enciendes un metal alomantico, con control + 1, empiezas a llenar si llevas la mente de metal del mismo metal y con alt + 1, lo decantas.

**Comment by TobibusFate** [comment]
Buenas!
Esto ya esta aplicado, aunque aun no se sube esa versión a curseforge

Aquí puedes descargar una versión beta con la implementación de las teclas: 
https://github.com/rudahee/Metallics-Arts/releases/tag/Pre-release-v1.3.1
