### ISSUE TITLE
Bug con el empuje de pepitas

### ISSUE THREAD

**Issue by Nagatosuke** [rudahee/Metallics-Arts#32]
Adjunto video, en la hotbar se ven las pepitas de cobre.
https://user-images.githubusercontent.com/117484083/203764446-e2215b2a-e82f-4b27-aa6b-2524600cbe55.mp4

**Comment by TobibusFate** [comment]
Buenas @Nagatosuke !
Ya esta subida la versión 1.4 y solucionado el problema ^^
