### ISSUE TITLE
No se muestra correctamente el almacenaje de las mentes de metal en la interfaz

### ISSUE THREAD

**Issue by ElPandaP** [rudahee/Metallics-Arts#37]
Se quedan vacías y al llenarse/vaciarse se colorean unos pixeles (como pasa en el de la izquierda de la foto) pero no sube, en la foto tengo las dos mentes a la mitad mas o menos
![image](https://user-images.githubusercontent.com/116599304/204882116-69c754ad-1b1a-4c21-bc42-2db2042e236f.png)

**Comment by rudahee** [comment]
duplicated
