### ISSUE TITLE
Nicrosil Mal funcionamiento

### ISSUE THREAD

**Issue by Andrulightweaver** [rudahee/Metallics-Arts#4]
El nicrosil feruquimico carga cuando no deberia cargarse

**Comment by rudahee** [comment]
¡Buenas @Andrulightweaver!

Se ha solucionado el error relacionado al nicrosil. 

Puedes encontrar la ultima [release aqui](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0) o en CurseForge en unas horas.

¡Nos vemos!
