### ISSUE TITLE
TP Oro/Duralumin no va.

### ISSUE THREAD

**Issue by CarlosMW312** [rudahee/Metallics-Arts#44]
Quemar Oro y Duralumin no te hace TP al lugar de tu muerte. Error reportado por un jugador y reproducido por un moderador.

**Comment by CarlosMW312** [comment]
Pasa lo mismo con el electrum.

**Comment by TobibusFate** [comment]
Buenas @CarlosMW312 !
El problema con el electrum/oro/malatium con duralumin es cosa del servidor en el cual esta corriendo
