### ISSUE TITLE
Opción para vaciar las mentes de metal rápidamente

### ISSUE THREAD

**Issue by Manuelmech** [rudahee/Metallics-Arts#49]
Estaría genial que se pudieran vaciar las mentes (propias, obviamente) rápida o instantáneamente con un botón especial. Sería útil:
- Para metales como el malatium: Por si tienes la mente llena de durabilidad de hierro y quieres empezar a almacenar durabilidad de diamante, por ejemplo, sin tener que vaciarla normalmente o conseguir 72 de atium otra vez.
- Para metales como el hierro, que en realidad siempre buscas tener vacíos.
- Para poder darle mentes de metal que nos sobren a otra persona (si al vaciar ambas mitades de una mente de metal se eliminara también el atributo de "dueño"): Sería distinto a la feruquimia de aluminio porque en realidad las mentes estarían como nuevas.

Con respecto a la tecla usada, podría ser la rueda del ratón, ya que el click derecho y el izquierdo se usan para almacenar y decantar.

**Comment by rudahee** [comment]
No se va a implementar, aun al menos.
