### ISSUE TITLE
Ettmetal Alomantico

### ISSUE THREAD

**Issue by Andrulightweaver** [rudahee/Metallics-Arts#5]
El ettmetal alomantico tiene mucho daño, mata al dragon de 2 explosiones

**Comment by rudahee** [comment]
¡Buenas @Andrulightweaver!

Se ha disminuido radicalmente el daño (Y el área de explosión) en esta release. La release esta disponible [aqui](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0)y estara en CurseForge en unas horas

¡Nos vemos!
