### ISSUE TITLE
Duralumin quema otro metal aunque lo apagues

### ISSUE THREAD

**Issue by Sanfre0** [rudahee/Metallics-Arts#54]
Si estas quemando duralumin y otro metal, por ejemplo oro y apagas el oro antes de consumir el duralumin por completo, al acabarse el duralumin quema tambien el oro aunque este apagado, no se si es aposta, ah y si enciendes y apagas duralumin, este se consume del todo

**Comment by rudahee** [comment]
Esto es un comportamiento esperado :)
