### ISSUE TITLE
Guide book translation fixes/enhancements

### ISSUE THREAD

**Issue by Manuelmech** [rudahee/Metallics-Arts#6]
**Feruchemy Section:**
Firstly, I think the chapter headings would read better as _"Feruchemical [Metal]"_, as that is the way pages like the Coppermind list their effects (e.g. Feruchemical Aluminum)
![image](https://user-images.githubusercontent.com/73159936/197840336-07e5ae8f-9abe-43fe-9114-67a01794aa21.png)
Secondly, words like identity may read better by starting with capital letters (Identity), as that is the way they are written in the books.
Also, "mente de metal" is written as "metalmind" in English (no space between), and "tap/tapping" is the word used for the process of retrieving stored attributes from a metalmind.
![image](https://user-images.githubusercontent.com/73159936/197841963-c8dd34dd-a805-403f-b0de-ecdfca7e4e38.png)
Suggested description for the chapter above:
> **Feruchemical Aluminum**
> _Storing:_
> By storing, you remove the Identity from your equipped metalminds.
> _Tapping:_
> By tapping, you seal your Identity into any equipped unkeyed metalminds.

(It should be noted that I have not tested if one can overwrite the ownership of a metalmind owned by another player by using Aluminum Feruchemy, so the last line of the suggested translation may be incorrect).

**Some other suggested changes:**
(The descriptions for atium are inverted in relation to the actual in-game effects. This may be an error in the book or in the power itself).

> Feruchemical Atium
> Storing:
> While storing, you start shining for other players.
> Tapping:
> While tapping, you become invisible.

![image](https://user-images.githubusercontent.com/73159936/197846477-aec1e3e2-1b5a-4cbd-8fb1-21982eab245c.png)
> Feruchemical Bendalloy
> Storing:
> While storing, your hunger bar starts slowly depleting.
> Tapping:
> While tapping, you hunger bar starts slowly replenishing.

![image](https://user-images.githubusercontent.com/73159936/197846712-19fb8bec-62a3-4b1d-bfc7-db97ffd66f5a.png)

Finally, the chapter headings for the craftings are not translated into English:
![image](https://user-images.githubusercontent.com/73159936/197849344-f1c27115-89bc-4aeb-986b-059628a7b934.png)

**Comment by rudahee** [comment]
@Manuelmech Thanks a lot. great job in your report!

**Comment by rudahee** [comment]
¡Buenas @Manuelmech !

Ya se han solucionado todos los problemas relacionados con la traducción ¡Por favor, sigue testeando!

Puedes encontrar la ultima [release aqui](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0) o en CurseForge en unas horas.

¡Nos vemos!
