### ISSUE TITLE
Mejoras en las mentes de aluminio y cobre

### ISSUE THREAD

**Issue by Manuelmech** [rudahee/Metallics-Arts#7]
Ya que las mentes de metal de aluminio no almacenan un atributo que se mida en segundos, podrían indicar su carga de manera similar a las mentes de lerasium:

> Aluminum: Is storing Identity

o

> Aluminum: Is tapping Identity

![image](https://user-images.githubusercontent.com/73159936/197852535-8fe4f1ae-ca86-4d5a-a060-94d7c3712287.png)

De manera similar, las mentes de cobre podrían mostrar su carga como _[Número] XP_ (actualmente la muestran como _[Número] pts xp_), para mejor estética en inglés.
![image](https://user-images.githubusercontent.com/73159936/197855421-bdcd7164-651d-4916-8bcd-1e7954ea0ad3.png)

**Comment by TobibusFate** [comment]
En el caso del aluminio, no seria problema buscar algo nuevo (aunque es un metal que no necesita que se indique su carga)

En el cobre, a que te refieres con Numero XP ? Al nivel de experiencia ? o a otra cosa ?

**Comment by Manuelmech** [comment]
> En el cobre, a que te refieres con Numero XP ? Al nivel de experiencia ? o a otra cosa ?

A nada importante, solo a cambiar "pts xp" a "XP" por estética

**Comment by rudahee** [comment]
¡Buenas @Manuelmech!

Se ha aplicado la mejora del aluminio, estamos intentando mejorar lo de la XP directamente con niveles, asi que dejamos la issue abierta hasta que tengamos una respuesta definitiva.

Puedes encontrar la ultima [release aqui](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0) o en 
CurseForge en unas horas.

¡Nos vemos!

**Comment by TobibusFate** [comment]
Ya terminamos los cambios relacionados con estas mentes de metal para la versión 1.4, que ya esta publicada ^^
Saludos!
