### ISSUE TITLE
Balanceo del hacha de obsidiana

### ISSUE THREAD

**Issue by Manuelmech** [rudahee/Metallics-Arts#8]
Sin encantar, el hacha de obsidiana hace el triple de daño (24) que una espada de netherite (8) y más del doble que el hacha de netherite (10), además de que puede ser encantada.
Si el daño fuera de 14-16, por ejemplo, con peltre alomántico dejaría a un jugador sin armadura a 1.5/0.5 corazones de vida, y con peltre feruquímico lo mataría de un golpe, además de que el hacha seguiría siendo más fuerte que un hacha de netherite con Filo V (13 de daño).
También podría reducirse su durabilidad y/o quitársele la capacidad de ser encantada.

**Comment by rudahee** [comment]
Buenas, ningún arma de obsidiana puede tener Mending. Eso es un hándicap bastante importante.

Además, hemos bajado el daño a 19 y bajado en 0.1 la velocidad, es muy poco probable encontrar a jugadores que vayan desnudos (normalmente se suele llevar al menos armadura de hierro), aun así ahora solo lo matarías si llevas peltre. Además, la penalización por fallar un golpe del hacha es enorme por el tiempo de "recarga" que tiene.

¡Gracias @Manuelmech por tu comentario!
Puedes probar el balanceo [en esta release](https://github.com/rudahee/Metallics-Arts/releases/tag/Release-v1.2.0). Estará en CurseForge en unas horas.
