### ISSUE TITLE
Sugerencias para el acero feruquímico y alomántico

### ISSUE THREAD

**Issue by Manuelmech** [rudahee/Metallics-Arts#9]
- El acero feruquímico podría afectar también la velocidad de ataque con armas y/o aplicar fatiga minera/prisa minera.
- El acero alomántico podría tener una combinación de teclas (como shift + espacio) que aplicara caída lenta mientras se mira (o no) hacia abajo con pepitas en el inventario o bloques de metal debajo, para permitir un mejor "aterrizaje".

**Comment by TobibusFate** [comment]
- Pondré para revisar lo del acero feruquimico ^^
- Y en cuanto al acero alomantico, lo dejamos en un principio asi para que tenga cierta dificultad el uso (para que no sea tan gratuito evitar daño por caída), aunque puede hacerse de otras formas

**Comment by TobibusFate** [comment]
Buenas, @Manuelmech 
Ya que otros poderes afectan la velocidad de minado. no vamos a implementar lo del acero feruquímico.
Muchas gracias por colaborar, sigue aportando ideas.
Un saludo
